source 'https://rubygems.org'

gem 'csv'
gem 'bigdecimal'
gem 'jekyll', '~> 4.0'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
gem 'jemoji'
gem 'webrick', '~> 1.8'
gem 'jekyll-gist'
gem 'jekyll-paginate'
